### ISSUE TITLE
Snap In Bricks

### ISSUE THREAD

**Issue by lgcproductions** [smerkousdavid/Neo.GPIO#1]
Hi, when running the code for the snap in sensors i'm getting a error message. Unsure if I need to install anything for the I2C or even enable it. :( Cheers for this great library. :)

udooer@neoudoo:~/Desktop/Neo.GPIO-1.0.0$ python SnapinSensorsExample.py
Traceback (most recent call last):
  File "SnapinSensorsExample.py", line 14, in <module>
    tempVal = temp.getTemp("f") # replace f with c to get celcius
  File "/home/udooer/Desktop/Neo.GPIO-1.0.0/neo/Neo.py", line 127, in getTemp
    with open("/sys/class/i2c-dev/i2c-1/device/1-0048/temp1_input", "r") as reader: # Read i2c millicel file
IOError: [Errno 2] No such file or directory: '/sys/class/i2c-dev/i2c-1/device/1-0048/temp1_input'

**Comment by smerkousdavid** [comment]
Thanks for reporting the error!

Two things that it might be, either the snapin sensor is the wrong sensor or not even plugged in(Make sure the in on the sensors is plugged in (The longer one and the shorter one to the neo)... Or it could be that the kernel doesn't detect the current sensor. To make sure it's 100% not the python scripts fault, try rebooting the Neo with the snapin sensor plugged in, this way the kernel has a chance to see the snapin sensor. If that still doesn't work just tell me and i'll figure something out

**Comment by lgcproductions** [comment]
Heya fella,

Powered off the boards, plugged in sensors and rebooted. Still getting the error on both Neo's. Tried it with just one sensor brick connected, then temp brick followed by baro brick. Swapped them around in the chain, so baro brick then temp brick. Same error.

There all connected correctly.

**Comment by smerkousdavid** [comment]
I figured out the problem, thanks for telling me I am currently fixing the problem

**Comment by lgcproductions** [comment]
Hey fella,

Not a problem. Big thanks for creating this library. Will keep you updated if I encounter any other errors.

**Comment by smerkousdavid** [comment]
This should fix it, try re installing the Neo library and running the code like this...

```
  echo udooer | sudo -S su -c 'python SnapinSensorsExample.py'
```

EDIT: I changed the code so it won't crash but just output that the sensor is not plugged in, so if you see that either you're not running as root or the sensor isn't plugged in

**Comment by lgcproductions** [comment]
Heya fella, 

Thinkit's possibly working.
 With just the temp brick plugged in, the output is as follows below. Looks like it's not detecting that brick. 

Snap in sensor is not plugged in!
Current temp from sensor 1: 32.0
Barometer is not plugged in!
Current pressure in (kPa):  0.0
Barometer is not plugged in!
Current temp from sensor 2: 0

Out put with baro meter. As you can see this brick is being detected and after breathing on the brick the temp goes up.

Snap in sensor is not plugged in!
Current temp from sensor 1: 32.0
Current pressure in (kPa):  100.4375
Current temp from sensor 2: 26.5

Snap in sensor is not plugged in!
Current temp from sensor 1: 32.0
Current pressure in (kPa):  100.44375
Current temp from sensor 2: 29.0

Out put code for both bricks plugged in. As you can see the temp has not changed between the two after breathing onto the temp brick.

Snap in sensor is not plugged in!
Current temp from sensor 1: 32.0
Current pressure in (kPa):  100.43975
Current temp from sensor 2: 28.6875

Snap in sensor is not plugged in!
Current temp from sensor 1: 32.0
Current pressure in (kPa):  100.4455
Current temp from sensor 2: 28.5625

Sorry for bugging you. Hopefully this feedback is helpful in any way. :) p.s the terminal line code did not work. Said it could not locate the file. Just logged in via VNC and re-downloaded. 

All the best,
Richard

**Comment by smerkousdavid** [comment]
This is really weird because mine is working perfectly, so here are two more things
 First using terminal change to the directory to where the python script is and run these commands

```
     sudo su 
```

Enter in your password which should be udooer

```
     sh -c 'python scriptname.py'
```

replace scriptname with the name of the file you want to run
if it still doesn't work just try the plain

```
     python scriptname.py
```

Second if for some weird reason you can't access the i2c try the commands manually

```
    echo udooer | sudo -S su -c 'rmmod lm75'
    echo udooer | sudo -S su -c 'modprobe lm75'
    echo udooer | sudo -S su -c 'echo lm75 0x48 >/sys/class/i2c-dev/i2c-1/device/new_device'
```

EDIT: After manually reseting the i2c device try running the python script as root again

**Comment by smerkousdavid** [comment]
Is it good?

**Comment by lgcproductions** [comment]
Hey up fella, sorry for the delay in replying. Slept in today then had to prepare for a gig.

Did what you said with this and it's working. :D

```
echo udooer | sudo -S su -c 'rmmod lm75'
echo udooer | sudo -S su -c 'modprobe lm75'
echo udooer | sudo -S su -c 'echo lm75 0x48 >/sys/class/i2c-dev/i2c-1/device/new_device'
```
