### ISSUE TITLE
LEDexample.py TypeError:__init__

### ISSUE THREAD

**Issue by lgcproductions** [smerkousdavid/Neo.GPIO#2]
Hey fella,

Hope you had a good Christmas. Just tried using your led example and it's coming up with this error.

Traceback (most recent call last):
  File "LEDexample.py", line 4, in <module>
    led= Led(2)
TypeError: **init**() take exactly 1 argument (2 given)

All the best,
RIchard

**Comment by smerkousdavid** [comment]
Thanks and to you too... The LED doesn't take an argument, the red led that's on your NEO is apparently not connected through pin 13 (Or it was just acting weird). So this is only for that red led which isn't put through GPIO. In my example I don't have the 2, try just like the error says removing the 2 argument

**Comment by lgcproductions** [comment]
Doh!, i'm an idiot. Removed the 2 and received some errors. Ran it with sudo and it blinked the SMD led by the green power led. 

Quick question how would I define using another pin instead of pin 13? Currently got a RGB led plugged into pin's 2,3,4.

Sorry to bug yourself. Hopefully i'll be able to contribute at some point for all the help you've given. :)

**Comment by smerkousdavid** [comment]
For those just use this gpio library like this, just like you would on an arduino

from neo import Gpio
from time import sleep

neo = Gpio()

red = 2
green = 3
blue = 4

neo.pinMode(red, neo.OUTPUT)
neo.pinMode(green, neo.OUTPUT)
neo.pinMode(blue, neo.OUTPUT)

while True:
    neo.digitalWrite(red, neo.HIGH)
    sleep(1)
    neo.digitalWrite(red, neo.LOW) 
    sleep(1)
    neo.digitalWrite(green, neo.HIGH)
    sleep(1)
    neo.digitalWrite(green, neo.LOW) 
    sleep(1)
    neo.digitalWrite(blue, neo.HIGH)
    sleep(1)
    neo.digitalWrite(blue, neo.LOW) 
    sleep(1)

EDIT: (More compact way of doing it

from neo import Gpio
from time import sleep

neo = Gpio()
pins = [2, 3, 4]

for pin in pins:
    neo.pinMode(pin, neo.OUTPUT)

while True:
    for pin in pins:
        neo.digitalWrite(pin, neo.HIGH)
        sleep(1)
        neo.digitalWrite(pin, neo.LOW)
        sleep(1)

**Comment by lgcproductions** [comment]
Cool, thought so. Had created a file for rotating through the rgb colours. using the led.on etc terms would have been nice and easy to quickly write the code. 

Cheers for the compact code. Will give it a play. python is all new to me. Think i'm learning quick enough for an 'old' dude.lol

Currently going to control led colour via inputs from a wii remote. :) cwiid works out of the can on the neo. :D

**Comment by smerkousdavid** [comment]
Thanks for that comment I added an example called easyGpioExample.py which uses states like on() off() and get()

**Comment by lgcproductions** [comment]
Nice. :D Will give them a look now as i'm playing with my robot for most of the day. Also thinking and kinda writing a motor part for this library. As I said i'm new to all this so kinda just following your example. lol

Currently got this. 

class Motor:
            def **init**(self, pin):
                self.pin = int(pin)
                self.gpio = Gpio()

```
            #Unsure if below code is needed.            
```

# def pinOUT(self):

# self.gpio.pinMode(self.pin,1)

#

# def pinIN(self):

# self.gpio.pinMode(self.pin, 1)

```
        def forwardL(self):
            self.gpio.pinMode(self.pin, 1)
```

**Comment by smerkousdavid** [comment]
You're right you want to know the truth is that when you call digitalWrite or Read I double check to see if the current pin state is in or out and reset that value, pinMode is there so the digitalWrite, which needed faster io speeds, doesn't have to handle it. If I was going to use motors I would wait until Udoo releases PWM, which I think will be soon. So it won't be just on and off. If you want to send a serial command to the cortex A9 and control PWM from there here is my Udoo Rc-Car example that uses an xbox controller https://www.hackster.io/smerkousdavid/udoo-rc-car-62b45e

If you don't want to here is how I would do it:

```
  from neo import Gpio
  from time import sleep

  class Motor:
       def __init__(self, pin, reversePin):
            self.pin = int(pin)
            self.reverse = int(reversePin)
            self.gpio = Gpio()
            self.gpio.pinMode(self.pin, 1)
            self.gpio.pinMode(self.reversePin, 1)

       def forward(self):
            self.gpio.digitalWrite(self.reverse, 0)
            self.gpio.digitalWrite(self.pin, 1)

       def backward(self):
            self.gpio.digitalWrite(self.reverse, 1)
            self.gpio.digitalWrite(self.pin, 1)

       def off(self):
            self.gpio.digitalWrite(self.pin, 0)
```

This example will just use 2 motors

```
  class Robot:
       def __init__(self, Left, Lreverse, Right, Rreverse):  
            self.left = Motor(int(Left), int(Lreverse))
            self.right = Motor(int(Right), int(Rreverse))

       def forward(self):
            self.left.backward()
            self.right.forward()

       def backward(self):
            self.left.forward()
            self.right.backward()

       def turnLeft(self):
            self.left.forwards()
            self.right.forward()

       def turnRight(self):
            self.left.backward()
            self.right.backward()

       def stop(self):
            self.left.off()
            self.right.off()
```

And now example of using it

```
  robot = Robot(2, 3, 4 , 5)
  robot.forward()
  sleep(8)
  robot.backward()
  sleep(8)
  robot.stop()
  sleep(1)
  robot.turnLeft()
  sleep(0.5)
  robot.turnRight()
  sleep(0.5)
  robot.stop()
```
