### ISSUE TITLE
Will this work on the UDOO Quad?

### ISSUE THREAD

**Issue by tsantor** [smerkousdavid/Neo.GPIO#5]
Not really an issue but a question.  Will this work on the UDOO Quad?  Can't find a library like `RPi.GPIO` that works on an UDOO Quad.

**Comment by tsantor** [comment]
Converted your `neo.py` to work with the Quad. Thanks!

**Comment by smerkousdavid** [comment]
That's great! If you want to make a pull request for the quad version (a flag or function to set the settings [gpio] for the quad), I would definitely consider accepting it as I currently don't have the time to map the gpio. I should rename this repo to include the names of all Udoo boards.
